---
- name: Provision a client server
  hosts: all
  gather_facts: no 

  tasks:
  - name: Wait for the system go get online
    wait_for_connection:
      delay: 0
      timeout: 600

  - name: Copy client
    copy:
      src: /app/src/server.php
      dest: /app/server.php

  - name: Copy start script client
    copy:
      src: /app/src/start_server.sh
      dest: /app/start_server.sh
      owner: ansible
      group: ansible
      mode: 0777

  - name: Start server
    command: "bash /app/start_server.sh"

